#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Fri Feb 06 20:44:39 EST 2026
a=false
another_furniture=true
farmersdelight=true
